### ISSUE TITLE
Typo in GRS67 mapping - 2 SNPs correspond to DQ92

### ISSUE THREAD

**Issue by tmajaria** [sethsh7/hla-prs-toolkit#2]
In the file hla-prs-toolkit/Snplists/T1D_GRS67/mapping_TOPMED.txt, both rs28746898 and rs9405117 are marked as DQ92.

From the file T1D_GRS67_1000G_nopalin_pos_hg19.xlsx, it looks like rs9405117 should correspond to DQ93.

**Comment by sethsh7** [comment]
Fixed in branch bugfixes_dec
